// Mocks generated by Mockito 5.4.6 from annotations
// in finance_tracking/test/features/transaction/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i16;

import 'package:finance_tracking/config/services/network_info_service.dart'
    as _i13;
import 'package:finance_tracking/config/services/supabase_error_handler_service.dart'
    as _i12;
import 'package:finance_tracking/features/auth/data/data_source/auth_local_data_source.dart'
    as _i10;
import 'package:finance_tracking/features/auth/data/models/local_user_profile_model.dart'
    as _i11;
import 'package:finance_tracking/features/transaction/data/data_source/transaction_local_data_source.dart'
    as _i8;
import 'package:finance_tracking/features/transaction/data/data_source/transaction_remote_data_source.dart'
    as _i4;
import 'package:finance_tracking/features/transaction/data/models/local_transaction_model.dart'
    as _i9;
import 'package:finance_tracking/features/transaction/data/models/transaction_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:uuid/data.dart' as _i15;
import 'package:uuid/uuid.dart' as _i14;
import 'package:uuid/uuid_value.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUuidValue_1 extends _i1.SmartFake implements _i3.UuidValue {
  _FakeUuidValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRemoteDataSource extends _i1.Mock
    implements _i4.TransactionRemoteDataSource {
  MockTransactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getUserId, []),
            ),
          )
          as String);

  @override
  _i6.Future<void> insertTransaction({required _i7.TransactionModel? data}) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [], {#data: data}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRemoteProfileBalance({
    required String? userId,
    required double? amount,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRemoteProfileBalance, [], {
              #userId: userId,
              #amount: amount,
              #type: type,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.TransactionModel>> getTransactions({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i7.TransactionModel>>.value(
              <_i7.TransactionModel>[],
            ),
          )
          as _i6.Future<List<_i7.TransactionModel>>);
}

/// A class which mocks [TransactionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDataSource extends _i1.Mock
    implements _i8.TransactionLocalDataSource {
  MockTransactionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveTransactions(
    List<_i9.LocalTransactionModel>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTransactions, [transactions]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.LocalTransactionModel>> getTransactions({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i9.LocalTransactionModel>>.value(
              <_i9.LocalTransactionModel>[],
            ),
          )
          as _i6.Future<List<_i9.LocalTransactionModel>>);

  @override
  _i6.Future<void> clearTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#clearTransactions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i10.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveUserProfile(_i11.LocalUserProfileModel? userProfile) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [userProfile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i11.LocalUserProfileModel?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i6.Future<_i11.LocalUserProfileModel?>.value(),
          )
          as _i6.Future<_i11.LocalUserProfileModel?>);

  @override
  _i6.Future<void> clearUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserProfile, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SupabaseErrorHandlerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseErrorHandlerService extends _i1.Mock
    implements _i12.SupabaseErrorHandlerService {
  MockSupabaseErrorHandlerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String handle(Object? e) =>
      (super.noSuchMethod(
            Invocation.method(#handle, [e]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#handle, [e]),
            ),
          )
          as String);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i13.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i14.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({Map<String, dynamic>? options, _i15.V1Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v1, [], {#options: options, #config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v1, [], {#options: options, #config: config}),
            ),
          )
          as String);

  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V1Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v1buffer,
              [buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v1obj({
    Map<String, dynamic>? options,
    _i15.V1Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1obj, [], {#options: options, #config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v1obj, [], {
                #options: options,
                #config: config,
              }),
            ),
          )
          as _i3.UuidValue);

  @override
  String v4({Map<String, dynamic>? options, _i15.V4Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v4, [], {#options: options, #config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v4, [], {#options: options, #config: config}),
            ),
          )
          as String);

  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V4Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v4buffer,
              [buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v4obj({
    Map<String, dynamic>? options,
    _i15.V4Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v4obj, [], {#options: options, #config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v4obj, [], {
                #options: options,
                #config: config,
              }),
            ),
          )
          as _i3.UuidValue);

  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5,
              [namespace, name],
              {#options: options, #config: config},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #v5,
                [namespace, name],
                {#options: options, #config: config},
              ),
            ),
          )
          as String);

  @override
  String v5FromBytes(
    String? namespace,
    _i16.Uint8List? name, {
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5FromBytes,
              [namespace, name],
              {#config: config},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #v5FromBytes,
                [namespace, name],
                {#config: config},
              ),
            ),
          )
          as String);

  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5buffer,
              [namespace, name, buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  List<int> v5FromBytesBuffer(
    String? namespace,
    _i16.Uint8List? name,
    List<int>? buffer, {
    _i15.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5FromBytesBuffer,
              [namespace, name, buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5obj,
              [namespace, name],
              {#options: options, #config: config},
            ),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(
                #v5obj,
                [namespace, name],
                {#options: options, #config: config},
              ),
            ),
          )
          as _i3.UuidValue);

  @override
  _i3.UuidValue v5FromBytesObj(
    String? namespace,
    _i16.Uint8List? name, {
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5FromBytesObj,
              [namespace, name],
              {#config: config},
            ),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(
                #v5FromBytesObj,
                [namespace, name],
                {#config: config},
              ),
            ),
          )
          as _i3.UuidValue);

  @override
  String v6({_i15.V6Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v6, [], {#config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v6, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v6buffer(
    List<int>? buffer, {
    _i15.V6Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v6buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v6obj({_i15.V6Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v6obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v6obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v7({_i15.V7Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v7, [], {#config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v7, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v7buffer(
    List<int>? buffer, {
    _i15.V7Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v7buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v7obj({_i15.V7Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v7obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v7obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v8({_i15.V8Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8, [], {#config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v8, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v8buffer(
    List<int>? buffer, {
    _i15.V8Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v8buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v8obj({_i15.V8Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v8obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v8g({_i15.V8GenericOptions? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8g, [], {#config: config}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#v8g, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v8gbuffer(
    List<int>? buffer, {
    _i15.V8GenericOptions? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v8gbuffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v8gobj({_i15.V8GenericOptions? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8gobj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v8gobj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);
}
