// Mocks generated by Mockito 5.4.6 from annotations
// in finance_tracking/test/features/get_goal/data/repositories/goal_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:finance_tracking/config/models/remote_goal_model.dart' as _i5;
import 'package:finance_tracking/config/services/network_info_service.dart'
    as _i10;
import 'package:finance_tracking/config/services/supabase_error_handler_service.dart'
    as _i8;
import 'package:finance_tracking/features/get_goal/data/data_source/local_goal_data_source.dart'
    as _i6;
import 'package:finance_tracking/features/get_goal/data/data_source/remote_goal_data_source.dart'
    as _i3;
import 'package:finance_tracking/features/get_goal/data/models/home_local_goal_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteGoalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteGoalDataSource extends _i1.Mock
    implements _i3.RemoteGoalDataSource {
  MockRemoteGoalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i4.Future<_i5.RemoteGoalModel?> getGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getGoal, []),
            returnValue: _i4.Future<_i5.RemoteGoalModel?>.value(),
          )
          as _i4.Future<_i5.RemoteGoalModel?>);
}

/// A class which mocks [LocalGoalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalGoalDataSource extends _i1.Mock
    implements _i6.LocalGoalDataSource {
  MockLocalGoalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveGoal(_i7.HomeLocalGoalModel? goal) =>
      (super.noSuchMethod(
            Invocation.method(#saveGoal, [goal]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.HomeLocalGoalModel?> getGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getGoal, []),
            returnValue: _i4.Future<_i7.HomeLocalGoalModel?>.value(),
          )
          as _i4.Future<_i7.HomeLocalGoalModel?>);

  @override
  _i4.Future<void> clearGoal() =>
      (super.noSuchMethod(
            Invocation.method(#clearGoal, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SupabaseErrorHandlerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseErrorHandlerService extends _i1.Mock
    implements _i8.SupabaseErrorHandlerService {
  MockSupabaseErrorHandlerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String handle(Object? e) =>
      (super.noSuchMethod(
            Invocation.method(#handle, [e]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#handle, [e]),
            ),
          )
          as String);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i10.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
