// Mocks generated by Mockito 5.4.6 from annotations
// in finance_tracking/test/features/streak/data/repositories/streak_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:finance_tracking/config/services/network_info_service.dart'
    as _i9;
import 'package:finance_tracking/config/services/supabase_error_handler_service.dart'
    as _i8;
import 'package:finance_tracking/features/streak/data/data_source/streak_local_data_source.dart'
    as _i7;
import 'package:finance_tracking/features/streak/data/data_source/streak_remote_data_source.dart'
    as _i4;
import 'package:finance_tracking/features/streak/domain/entities/streak_entity.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreakEntity_2 extends _i1.SmartFake implements _i3.StreakEntity {
  _FakeStreakEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StreakRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRemoteDataSource extends _i1.Mock
    implements _i4.StreakRemoteDataSource {
  MockStreakRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getUserId, []),
            ),
          )
          as String);

  @override
  _i6.Future<DateTime> getServerTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getServerTimestamp, []),
            returnValue: _i6.Future<DateTime>.value(
              _FakeDateTime_1(this, Invocation.method(#getServerTimestamp, [])),
            ),
          )
          as _i6.Future<DateTime>);

  @override
  _i6.Future<_i3.StreakEntity> getStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, []),
            returnValue: _i6.Future<_i3.StreakEntity>.value(
              _FakeStreakEntity_2(this, Invocation.method(#getStreak, [])),
            ),
          )
          as _i6.Future<_i3.StreakEntity>);

  @override
  _i6.Future<void> updateStreak({
    required int? currentStreak,
    required int? longestStreak,
    required DateTime? lastCheckInDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, [], {
              #currentStreak: currentStreak,
              #longestStreak: longestStreak,
              #lastCheckInDate: lastCheckInDate,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [StreakLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakLocalDataSource extends _i1.Mock
    implements _i7.StreakLocalDataSource {
  MockStreakLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.StreakEntity?> getStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, []),
            returnValue: _i6.Future<_i3.StreakEntity?>.value(),
          )
          as _i6.Future<_i3.StreakEntity?>);

  @override
  _i6.Future<void> saveStreak({
    required int? currentStreak,
    required int? longestStreak,
    required DateTime? lastCheckInDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveStreak, [], {
              #currentStreak: currentStreak,
              #longestStreak: longestStreak,
              #lastCheckInDate: lastCheckInDate,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SupabaseErrorHandlerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseErrorHandlerService extends _i1.Mock
    implements _i8.SupabaseErrorHandlerService {
  MockSupabaseErrorHandlerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String handleError(Object? e) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [e]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#handleError, [e]),
            ),
          )
          as String);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
